{{- $replicas := .Values.replicas | int }}
{{- $storageSize := .Values.storage.size }}
{{- $storageClassName := .Values.storage.className }}
{{- range $i := until $replicas }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-{{ $i }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ $storageSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $storageClassName }}
  local:
    path: /mnt/disks/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kworker{{ add $i 1 }}
---
{{- end }}
