apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-0
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.className }}
  local:
    path: /mnt/disks/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kworker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.className }}
  local:
    path: /mnt/disks/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kworker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.className }}
  local:
    path: /mnt/disks/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kworker3
